# Site settings
author: Michael Pieschel
title: The Tech Explorator
header-img: img/home-bg.png
email: sixtyhectares@yahoo.com
copyright_name: Michael Pieschel
description: > # this means to ignore newlines until "baseurl:"
  let explorator={one_who:["explores","examines closely"], a:"searcher"}
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  Xplor8r
linkedin_username: michael-pieschel
youtube_id: UC4O_-OpPQPCMEVYpwGo58UA
meetup_id: 274219972
# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
